repos:
#  Backend
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      - id: ruff
        files: ^backend/.*\.py$
      - id: ruff-format
        files: ^backend/.*\.py$

#  Frontend
